<a href="https://colab.research.google.com/github/rajkhatana/LEARNING-ANALYTICS/blob/master/BreastCancer_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from keras.utils import to_categorical
np.random.seed(10)

Using TensorFlow backend.


In [0]:
# Importing and cleaning data using pandas library
data = pd.read_csv('C_data.csv')
del data['Unnamed: 32']


In [0]:
## Observe the data
data

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
5      843786         M  ...          0.3985                  0.12440
6      844359         M  ...          0.3063                  0.08368
7    84458202         M  ...          0.3196                  0.11510
8      844981         M  ...          0.4378                  0.10720
9    84501001         M  ...          0.4366                  0.20750
10     845636         M  ...          0.2948                  0.08452
11   84610002         M  ...          0.3792                  0.10480
12     846226         M  ...          0.3176                  0.10230
13     846381         M  ...          0.2809                  0.06287
14   84667401         M  ...          0.3596                  0.14310
15   84799002         M  ...          0.4218                  0.13410
16     848406         M  ...          0.3029                  0.08216
17   84862001         M  ...          0.3706                  0.11420
18     849014         M  ...          0.2768                  0.07615
19    8510426         B  ...          0.2977                  0.07259
20    8510653         B  ...          0.3184                  0.08183
21    8510824         B  ...          0.2450                  0.07773
22    8511133         M  ...          0.4667                  0.09946
23     851509         M  ...          0.2822                  0.07526
24     852552         M  ...          0.3613                  0.09564
25     852631         M  ...          0.4066                  0.10590
26     852763         M  ...          0.4264                  0.12750
27     852781         M  ...          0.2341                  0.07421
28     852973         M  ...          0.4027                  0.09876
29     853201         M  ...          0.2756                  0.07919
..        ...       ...  ...             ...                      ...
539    921362         B  ...          0.2790                  0.10660
540    921385         B  ...          0.2329                  0.08134
541    921386         B  ...          0.3187                  0.10230
542    921644         B  ...          0.2722                  0.06956
543    922296         B  ...          0.2473                  0.06443
544    922297         B  ...          0.2249                  0.08492
545    922576         B  ...          0.2642                  0.06953
546    922577         B  ...          0.2681                  0.07399
547    922840         B  ...          0.2691                  0.09479
548    923169         B  ...          0.2552                  0.07920
549    923465         B  ...          0.3059                  0.07626
550    923748         B  ...          0.2458                  0.06592
551    923780         B  ...          0.3169                  0.08032
552    924084         B  ...          0.2407                  0.06484
553    924342         B  ...          0.2435                  0.07393
554    924632         B  ...          0.2372                  0.07242
555    924934         B  ...          0.2226                  0.08283
556    924964         B  ...          0.2262                  0.06742
557    925236         B  ...          0.2475                  0.06969
558    925277         B  ...          0.2258                  0.08004
559    925291         B  ...          0.2112                  0.08732
560    925292         B  ...          0.2250                  0.08321
561    925311         B  ...          0.1566                  0.05905
562    925622         M  ...          0.4089                  0.14090
563    926125         M  ...          0.2929                  0.09873
564    926424        

In [0]:
## We have left first two columns and taken other columns as input features
X = data.iloc[:, 2:].values

# 2nd column is output labels
y = data.iloc[:, 1].values

In [0]:
y.shape

(569,)

In [0]:
## Convert the output labels to numbers : M->0; B-> 1
## Store the output in Y_v
Y_v = []

# YOUR CODE HERE
for i in y:
  if i=='B':
    Y_v.append(1)
  else:
    Y_v.append(0)

In [0]:
len(Y_v)

569

In [0]:
"""Test for Y_v"""

'Test for Y_v'

In [0]:
### One-hot encode Y_v
def oneHot(y, Ny):
    '''
    Input:
        y: an int in {0, 1}
        Ny: Number of classes, e.g., 2 here.
    Output:
        Y: a vector of Ny (=2) tuples
    '''
    # YOUR CODE HERE
    return to_categorical(y, num_classes = Ny)
    


In [0]:
"""Test for one-hot"""
assert np.all(oneHot(0,3)==np.array([1,0,0]))


In [0]:
from keras.utils import to_categorical

Ny = len(np.unique(Y_v)) # Ny is number of categories/classes


Y_v = to_categorical(Y_v[:], num_classes = Ny) # 

In [0]:
### Split data into train and test. Keep 10% of samples for testing
## Divide the data into these variables - X_train, X_test, y_train, y_test
# YOUR CODE HERE
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y_v, test_size = 0.10, random_state = 1)

In [0]:
"""test for splitting"""
assert(X_train.shape[0] == 512)

In [0]:
## Normalize the Data
def findMeanStddev(X):
    '''
    Input: 
        X: a matrix of size (no. of samples, dimension of each sample)
    Output:
        mean: mean of samples in X (same size as X)
        stddev: element-wise std dev of sample in X (same size as X)
    '''
    # YOUR CODE HERE
    mean = X.mean(axis=0) 
    stddev = X.std(axis=0)
    return mean , stddev
 
def normalizeX(X, mean, stddev):
    '''
    Input:
        X: a matrix of size (no. of samples, dimension of each sample)
        mean: mean of samples in X (same size as X)
        stddev: element-wise std dev of sample in X (same size as X) 
    Output:
        Xn: X modified to have 0 mean and 1 std dev
    '''
    # YOUR CODE HERE
    X_ = (X - mean)/stddev
    return X_


In [0]:
x=np.array([[1,2,3,4,5,6],[1,3,5,6,7,9],[0,4,7,2,4,6]])
print(x)
print(x.mean(axis=0))
print('\n')
print(x.std(axis=0))
print('\n')
print(x.mean(axis=0)/x.std(axis=0))
print('\n')
print(x-x.mean(axis=0))
print('\n')
print((x-x.mean(axis=0))/x.std(axis=0))

[[1 2 3 4 5 6]
 [1 3 5 6 7 9]
 [0 4 7 2 4 6]]
[0.66666667 3.         5.         4.         5.33333333 7.        ]


[0.47140452 0.81649658 1.63299316 1.63299316 1.24721913 1.41421356]


[1.41421356 3.67423461 3.06186218 2.44948974 4.27617987 4.94974747]


[[ 0.33333333 -1.         -2.          0.         -0.33333333 -1.        ]
 [ 0.33333333  0.          0.          2.          1.66666667  2.        ]
 [-0.66666667  1.          2.         -2.         -1.33333333 -1.        ]]


[[ 0.70710678 -1.22474487 -1.22474487  0.         -0.26726124 -0.70710678]
 [ 0.70710678  0.          0.          1.22474487  1.33630621  1.41421356]
 [-1.41421356  1.22474487  1.22474487 -1.22474487 -1.06904497 -0.70710678]]


In [0]:

mean, stddev = findMeanStddev(x)
normalizeX(x, mean, stddev)

array([[ 0.70710678, -1.22474487, -1.22474487,  0.        , -0.26726124,
        -0.70710678],
       [ 0.70710678,  0.        ,  0.        ,  1.22474487,  1.33630621,
         1.41421356],
       [-1.41421356,  1.22474487,  1.22474487, -1.22474487, -1.06904497,
        -0.70710678]])

In [0]:
"""test for normalizeX"""


'test for normalizeX'

In [0]:
#Normalize X_train data
mean, stddev = findMeanStddev(X_train)
X_train=normalizeX(X_train, mean, stddev)
mean, stddev = findMeanStddev(X_test)
X_test=normalizeX(X_test, mean, stddev)



In [0]:
#Normalize X_test data
mean2, stddev2 =findMeanStddev(X_test)
normalizeX(X_test, mean2, stddev2)

array([[ 0.11371369, -1.39054784,  0.22024797, ..., -0.12915533,
        -0.20586772,  0.49504479],
       [-0.32367383, -0.11469126, -0.29907544, ...,  1.6522667 ,
         1.78513096,  2.05556829],
       [-0.38697991, -0.83440523, -0.41957205, ..., -0.22367976,
         0.8202481 ,  0.72229376],
       ...,
       [-1.31009777,  0.01071345, -1.31947808, ..., -1.30907475,
         0.478828  , -0.22961349],
       [-0.11361272, -0.67083387, -0.17221458, ..., -1.01223168,
        -0.48048823, -0.4175774 ],
       [-0.39849011, -0.74989336, -0.44545337, ..., -0.64631305,
         0.15967444, -0.87026218]])

#### Create model. 
- Choose the number of hidden layers, neurons, activations, loss function, learning rate and optimizers on your own.
- Report accuracy metric
- Use no more than 100 epochs

Evalutaion
- 2 points if accuracy > 0.80
- +1 point if accuracy > 0.90
- +1 point if accuracy > 0.95

In [0]:
import keras
# YOUR CODE HERE
from keras.models import Sequential
from keras.layers import Dense
#create model
model = Sequential()



#add model layers

model.add(Dense(10, input_dim=X_train.shape[1], activation='sigmoid'))
model.add(Dense(20, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(Ny, activation='softmax')) # 'sigmoid'
# Compile model

W0614 05:44:17.285344 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0614 05:44:17.304866 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0614 05:44:17.308365 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) # 'binary_crossentropy', 'adam', 'adagrad', 'sgd'

W0614 05:44:17.468617 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0614 05:44:17.497610 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                310       
_________________________________________________________________
dense_2 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_3 (Dense)              (None, 10)                210       
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 22        
Total params: 762
Trainable params: 762
Non-trainable params: 0
_________________________________________________________________


In [0]:
# Fit the model
model.fit(X_train, y_train, epochs=100, batch_size=100)

W0614 05:44:17.620891 139758495418240 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0614 05:44:17.680081 139758495418240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
512/512 [==============================] - 1s 2ms/step - loss: 0.6667 - acc: 0.6309
Epoch 2/100
512/512 [==============================] - 0s 55us/step - loss: 0.6581 - acc: 0.6309
Epoch 3/100
512/512 [==============================] - 0s 54us/step - loss: 0.6525 - acc: 0.6309
Epoch 4/100
512/512 [==============================] - 0s 50us/step - loss: 0.6476 - acc: 0.6309
Epoch 5/100
512/512 [==============================] - 0s 51us/step - loss: 0.6445 - acc: 0.6309
Epoch 6/100
512/512 [==============================] - 0s 48us/step - loss: 0.6404 - acc: 0.6309
Epoch 7/100
512/512 [==============================] - 0s 46us/step - loss: 0.6354 - acc: 0.6309
Epoch 8/100
512/512 [==============================] - 0s 47us/step - loss: 0.6295 - acc: 0.6309
Epoch 9/100
512/512 [==============================] - 0s 46us/step - loss: 0.6227 - acc: 0.6309
Epoch 10/100
512/512 [==============================] - 0s 49us/step - loss: 0.6159 - acc: 0.6309
Epoch 11/100
512/512 [========

In [0]:
# calculate predictions
predictions = model.predict(X_train)
# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded)

[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0,

In [0]:
"""Test for model"""


'Test for model'

In [0]:
# evaluate the model
scores = model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

57/57 [==============================] - 0s 652us/step

acc: 100.00%


In [0]:
from sklearn.metrics import classification_report, confusion_matrix  
predictions = np.argmax(model.predict(X_test), axis=1)
y_test = np.argmax(y_test,axis=1)
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[23  0]
 [ 0 34]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        34

    accuracy                           1.00        57
   macro avg       1.00      1.00      1.00        57
weighted avg       1.00      1.00      1.00        57

